/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CreateTaskResult = { 'ok' : Task } |
  { 'err' : string };
export type DeleteTaskResult = { 'ok' : boolean } |
  { 'err' : string };
export interface Task {
  'id' : TaskId,
  'title' : string,
  'owner' : Principal,
  'createdAt' : bigint,
  'completed' : boolean,
  'description' : string,
  'updatedAt' : bigint,
}
export type TaskId = string;
export type ToggleTaskResult = { 'ok' : Task } |
  { 'err' : string };
export type UpdateTaskResult = { 'ok' : Task } |
  { 'err' : string };
export interface _SERVICE {
  'createTask' : ActorMethod<[string, string], CreateTaskResult>,
  'deleteTask' : ActorMethod<[TaskId], DeleteTaskResult>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'toggleTask' : ActorMethod<[TaskId], ToggleTaskResult>,
  'updateTask' : ActorMethod<[TaskId, string, string], UpdateTaskResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];