/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TaskId = IDL.Text;
export const Task = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const CreateTaskResult = IDL.Variant({ 'ok' : Task, 'err' : IDL.Text });
export const DeleteTaskResult = IDL.Variant({
  'ok' : IDL.Bool,
  'err' : IDL.Text,
});
export const ToggleTaskResult = IDL.Variant({ 'ok' : Task, 'err' : IDL.Text });
export const UpdateTaskResult = IDL.Variant({ 'ok' : Task, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'createTask' : IDL.Func([IDL.Text, IDL.Text], [CreateTaskResult], []),
  'deleteTask' : IDL.Func([TaskId], [DeleteTaskResult], []),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'toggleTask' : IDL.Func([TaskId], [ToggleTaskResult], []),
  'updateTask' : IDL.Func([TaskId, IDL.Text, IDL.Text], [UpdateTaskResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TaskId = IDL.Text;
  const Task = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const CreateTaskResult = IDL.Variant({ 'ok' : Task, 'err' : IDL.Text });
  const DeleteTaskResult = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const ToggleTaskResult = IDL.Variant({ 'ok' : Task, 'err' : IDL.Text });
  const UpdateTaskResult = IDL.Variant({ 'ok' : Task, 'err' : IDL.Text });
  
  return IDL.Service({
    'createTask' : IDL.Func([IDL.Text, IDL.Text], [CreateTaskResult], []),
    'deleteTask' : IDL.Func([TaskId], [DeleteTaskResult], []),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'toggleTask' : IDL.Func([TaskId], [ToggleTaskResult], []),
    'updateTask' : IDL.Func(
        [TaskId, IDL.Text, IDL.Text],
        [UpdateTaskResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };